// components/molecules/ModeCard.vue
<template>
  <app-button type="text" :class="{'mode-card-selected': name===currentMode}" class="mode-card" @click="changeMode">
      <img class="mode-icon" :src="icon" :alt="name" width="28px" v-if="showIcon">
      <span class="mode-name"> {{name}} </span>
  </app-button>
</template>

<script>
import { mapGetters, mapMutations } from 'vuex'
import AppButton from '../atoms/AppButton.vue'
export default {
  name: "ModeCard",
  components: { AppButton },
  props: {
    icon: {
      type: String,
      default: '/svg/tetradic.svg'
    },
    name: {
      type: String,
      default: 'Mode'
    }
  },
  methods: {
    ...mapMutations({changeCurrentMode: 'mode/changeCurrentMode'}),
    changeMode() {
      this.changeCurrentMode(this.name)
    }
  },
  computed: {
    ...mapGetters({currentMode: 'mode/currentMode'}),
    showIcon() {
      return window.innerWidth >= 1440
    }
  }
}
</script>

<style scoped>
  .mode-card {
    width: 230px;
    height: 50px;
    border: 2px solid #F1F1F1;
    box-sizing: border-box;
    border-radius: 7px;
    display: flex;
    align-items: center;
    background-color: white;
    transition: ease-in 0.2s;
  }
  .mode-card:hover {
    background-color: rgba(0,0,0,0.05) !important;
  }
  .mode-card:active {
    background-color: rgba(0,0,0,0.1) !important;
  }
  .mode-card-selected {
    background-color: #F1F1F1 !important;
  }
  .mode-icon {
    margin-left: 8px;
  }
  .mode-name {
    margin-left: 10px;
    text-transform: uppercase;
    font-size: 16px;
    color: rgba(0, 0, 0, 0.8)
  }
  @media (max-width: 1439px) {
    .mode-card {
    width: 150px;
    height: 40px;
  }
  .mode-name {
    margin: 0 auto 0 auto;
  }
  }
</style>

// src/components/mode-card.tsx
import React from 'react';
import withStyles from 'react-jss';
import m1 from './img/svg/square.svg';
import m2 from './img/svg/analogous.svg';
import m3 from './img/svg/complementary.svg';
import m4 from './img/svg/davidstar.svg';
import m5 from './img/svg/isosceles.svg';
import m6 from './img/svg/monochram.svg';
import m7 from './img/svg/tetradic.svg';
import m8 from './img/svg/triadic.svg';

const styles = {
    '@import': 'url(https://fonts.googleapis.com/css2?family=Ropa+Sans&display=swap)',
    ModeCard: {
        width: 230,
        height: 50,
        border: {
            width: 2,
            style: 'solid',
            color: '#F1F1F1',
            radius: 7,
        },
        alingItem: 'center',
        boxSizing: 'border-box',
        background: {
            color: 'white',
        },
        transition: 'ease-in 0.2s',
        display: 'flex',
        '&:hover': {
            background: {
                color: 'rgba(0,0,0,0.05)',
            },
        },
        '&:active': {
            background: {
                color: 'rgba(0,0,0,0.1)',
        }
        }
    },
    ModeIcon: {
        width: 40,
        height: 40,    
    },
    ModeName: {
        margin: {
            left: 20,
            top: 13,
        },
        textTransform: 'uppercase',
        font: {
            family: 'Ropa Sans',
            size: 15,
        },
        color: 'rgba(0, 0, 0, 0.8)',
    }
}


const UnstyledModeCard = ({classes, num, forModeChange, setMode, updateColorPickers}) => {

    const objects = [
        {
          name: 'square',
          icon: m1,
        },
        {
            name: 'analogous',
            icon: m2,
        },
        {
            name: 'complementary',
            icon: m3,
        },
        {
            name: 'davidstar',
            icon: m4,
        },
        {
            name: 'isosceles',
            icon: m5
        },
        {
            name: 'monochram',
            icon: m6
        },
        {
            name: 'tetradic',
            icon: m7
        },
        {
            name: 'triadic',
            icon: m8
        }
    ]

    const selectMode = () => {
        setMode(objects[num].name);
        forModeChange.mode = objects[num].name;
        updateColorPickers(forModeChange);
    };

    return (
    <>
        <button className={classes.ModeCard} onClick={selectMode} >
            <img className={classes.ModeIcon} src={ objects[num].icon } alt={ objects[num].name }/>
            <span className={classes.ModeName}> { objects[num].name } </span>
        </button>
    </>
    );
}

const ModeCard = withStyles(styles)(UnstyledModeCard);
export default ModeCard;
